# Generated by Django 5.1.6 on 2025-03-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_title_expense_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='user',
        ),
        migrations.AddField(
            model_name='expense',
            name='user_id',
            field=models.IntegerField(default=1),
        ),
    ]
